[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.3.1" }

[libraries]
kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version = "5.9.0" }
kotest-framework-engine-jvm = { group = "io.kotest", name = "kotest-framework-engine-jvm", version = "5.9.1" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version = "5.9.0" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version = "2.0.0" }
google-gson = { group = "com.google.code.gson", name = "gson", version = "2.11.0" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version = "5.10.2" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.10.2" }
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.26.0" }